<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>YokiFrame.Editor</AssemblyName>
    <RootNamespace>YokiFrame</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);GODOT;TOOLS</DefineConstants>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**/*.cs"
             Exclude="Adapters/**/*.cs;**/Tests/**/*.cs;bin/**/*.cs;obj/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Runtime/YokiFrame.csproj">
      <AdditionalProperties>YokiFrameToolsBuild=True</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

</Project>
