#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace YokiFrame
{
    /// <summary>
    /// 使用 CodeGenKit 生成 UIKit 用户脚本和 Designer partial，并保证用户脚本不被覆盖。
    /// </summary>
    internal static partial class UIKitPanelCodeGenerator
    {
        private const string AUTO_GENERATED_HEADER =
            "//------------------------------------------------------------------------------\n"
            + "// <auto-generated>\n"
            + "//     This code was generated by YokiFrame UIKit.\n"
            + "// </auto-generated>\n"
            + "//------------------------------------------------------------------------------\n\n";

        /// <summary>
        /// 生成当前布局需要的全部源码；本阶段只在内存中构建，不写入磁盘。
        /// </summary>
        internal static Dictionary<string, string> BuildSources(
            UIKitPanelCodeLayout layout,
            UIKitBindScanResult scan,
            Dictionary<string, string> relocations = null)
        {
            if (layout == null) throw new ArgumentNullException(nameof(layout));
            if (scan == null) throw new ArgumentNullException(nameof(scan));
            if (scan.HasErrors) throw CreateDiagnosticException(scan);
            relocations ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            HashSet<string> expected = UIKitGeneratedCodeMigration.Prepare(layout, scan.Nodes, null, null, relocations);
            UIKitGeneratedCodeCleanup.ConfirmAndDelete(layout.PanelFolder, expected, !Application.isBatchMode);

            ValidateTypeLocation(layout.ScriptNamespace + "." + layout.PanelName, layout.AssemblyName,
                layout.PanelScriptPath, layout.ScriptFolder + "/" + layout.PanelName + "/" + layout.PanelName + ".cs", relocations);
            ValidateNodeOwnership(layout, scan.Nodes, relocations);
            IUIKitCodeTemplate template = UIKitCodeTemplateRegistry.Require(layout.CodeTemplate);
            Dictionary<string, string> sources = new(StringComparer.OrdinalIgnoreCase);
            AddIfMissing(
                sources,
                layout.PanelScriptPath,
                relocations,
                ApplyTemplate(
                    template,
                    UIKitCodeTemplatePart.PanelUser,
                    CreateTemplateContext(layout, layout.PanelName, "Panel", string.Empty),
                    BuildPanelUserSource(layout)));
            AddSource(
                sources,
                layout.PanelDesignerPath,
                ApplyTemplate(
                    template,
                    UIKitCodeTemplatePart.PanelDesigner,
                    CreateTemplateContext(layout, layout.PanelName, "Panel", string.Empty),
                    BuildPanelDesignerSource(layout, scan.Nodes)));
            AddNodeSources(layout, scan.Nodes, sources, template, relocations);
            return sources;
        }

        /// <summary>
        /// 只生成当前 UIElement/UIComponent owner Designer，并递归补齐其内部生成类型。
        /// </summary>
        internal static Dictionary<string, string> BuildOwnerSources(
            UIKitPanelCodeLayout layout,
            UIKitBindScanResult scan,
            UIKitGeneratedOwnerKind ownerKind,
            Type ownerType,
            string designerPath,
            Dictionary<string, string> relocations = null)
        {
            if (layout == null) throw new ArgumentNullException(nameof(layout));
            if (scan == null) throw new ArgumentNullException(nameof(scan));
            if (scan.HasErrors) throw CreateDiagnosticException(scan);
            relocations ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            ValidateGeneratedOwnerType(ownerKind, ownerType);
            if (ownerKind == UIKitGeneratedOwnerKind.Component) layout = layout.ForComponent(ownerType.Name);
            HashSet<string> expected = UIKitGeneratedCodeMigration.Prepare(layout, scan.Nodes, ownerKind, ownerType.Name, relocations);
            UIKitGeneratedCodeCleanup.ConfirmAndDelete(GetCleanupRoot(layout, ownerKind, ownerType.Name), expected, !Application.isBatchMode);
            ValidateNodeOwnership(layout, scan.Nodes, relocations);
            string assetPath = RequireDesignerPath(designerPath);
            string namespaceName = CodeGenKit.RequireQualifiedName(
                ownerType.Namespace,
                nameof(ownerType.Namespace));
            string typeName = CodeGenKit.RequireIdentifier(ownerType.Name, nameof(ownerType.Name));

            IUIKitCodeTemplate template = UIKitCodeTemplateRegistry.Require(layout.CodeTemplate);
            Dictionary<string, string> sources = new(StringComparer.OrdinalIgnoreCase);
            AddSource(
                sources,
                assetPath,
                ApplyTemplate(
                    template,
                    UIKitCodeTemplatePart.BindingDesigner,
                    CreateTemplateContext(layout, typeName, ownerKind.ToString(), ownerKind.ToString()),
                    BuildBindingOwnerDesignerSource(layout, namespaceName, typeName, scan.Nodes)));
            AddNodeSources(layout, scan.Nodes, sources, template, relocations);
            return sources;
        }

        /// <summary>以文件集事务提交生成源码，任一文件失败时恢复本次已修改文件。</summary>
        internal static bool CommitSources(
            Dictionary<string, string> sources,
            Dictionary<string, string> relocations = null)
        {
            if (sources == null) throw new ArgumentNullException(nameof(sources));
            relocations ??= new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            List<SourceFileSnapshot> snapshots = CaptureSnapshots(sources, relocations);
            bool changed = false;
            try
            {
                AssetDatabase.StartAssetEditing();
                foreach (KeyValuePair<string, string> relocation in relocations)
                {
                    EnsureFolder(UIKitPanelCodeLayout.AssetDirectory(relocation.Value));
                    string error = AssetDatabase.MoveAsset(relocation.Key, relocation.Value);
                    if (!string.IsNullOrEmpty(error)) throw new IOException(relocation.Key + " -> " + relocation.Value + ": " + error);
                    changed = true;
                }
                foreach (KeyValuePair<string, string> source in sources)
                {
                    string absolutePath = UIKitPanelCodeLayout.ToAbsolutePath(source.Key);
                    CodeGenerationFileResult result = CodeGenKit.WriteTextToFile(absolutePath, source.Value);
                    changed |= result != CodeGenerationFileResult.Unchanged;
                }
                return changed;
            }
            catch (Exception exception)
            {
                try
                {
                    RestoreSnapshots(snapshots);
                    AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
                }
                catch (Exception rollbackException)
                {
                    throw new AggregateException("UIKit 代码生成失败且回滚也失败。", exception, rollbackException);
                }
                throw;
            }
            finally { AssetDatabase.StopAssetEditing(); }
        }

        /// <summary>创建生成、迁移和清理共同使用的文件快照。</summary>
        private static List<SourceFileSnapshot> CaptureSnapshots(
            Dictionary<string, string> sources,
            Dictionary<string, string> relocations)
        {
            HashSet<string> paths = new(StringComparer.OrdinalIgnoreCase);
            foreach (string path in sources.Keys) paths.Add(path);
            foreach (KeyValuePair<string, string> relocation in relocations)
            {
                paths.Add(relocation.Key);
                paths.Add(relocation.Value);
                paths.Add(relocation.Key + ".meta");
                paths.Add(relocation.Value + ".meta");
            }
            List<string> ordered = new(paths);
            ordered.Sort(StringComparer.OrdinalIgnoreCase);
            List<SourceFileSnapshot> snapshots = new(ordered.Count);
            foreach (string assetPath in ordered)
            {
                string absolutePath = UIKitPanelCodeLayout.ToAbsolutePath(assetPath);
                bool existed = File.Exists(absolutePath);
                string source = sources.TryGetValue(assetPath, out string generated) ? generated : string.Empty;
                snapshots.Add(new SourceFileSnapshot(absolutePath, source, existed,
                    existed ? File.ReadAllBytes(absolutePath) : Array.Empty<byte>()));
            }
            return snapshots;
        }

        /// <summary>确保迁移目标目录存在。</summary>
        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            EnsureFolder(UIKitPanelCodeLayout.AssetDirectory(path));
            AssetDatabase.CreateFolder(UIKitPanelCodeLayout.AssetDirectory(path), Path.GetFileName(path));
        }

        /// <summary>恢复生成、迁移和清理事务前的文件状态。</summary>
        private static void RestoreSnapshots(List<SourceFileSnapshot> snapshots)
        {
            for (var index = snapshots.Count - 1; index >= 0; index--)
            {
                SourceFileSnapshot snapshot = snapshots[index];
                if (snapshot.Existed)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(snapshot.AbsolutePath));
                    File.WriteAllBytes(snapshot.AbsolutePath, snapshot.OriginalBytes);
                }
                else if (File.Exists(snapshot.AbsolutePath)) File.Delete(snapshot.AbsolutePath);
            }
        }

        /// <summary>记录一个待提交源码文件的旧状态和新文本。</summary>
        private sealed class SourceFileSnapshot
        {
            /// <summary>创建文件事务快照。</summary>
            internal SourceFileSnapshot(string absolutePath, string source, bool existed, byte[] originalBytes)
            {
                AbsolutePath = absolutePath;
                Source = source;
                Existed = existed;
                OriginalBytes = originalBytes;
            }

            internal string AbsolutePath { get; }
            internal string Source { get; }
            internal bool Existed { get; }
            internal byte[] OriginalBytes { get; }
        }

        /// <summary>为每个 UIKit 生成文件统一导入 Unity UI 与框架常用命名空间。</summary>
        /// <param name="build">在标准 using 之后构建文件声明的回调。</param>
        /// <returns>使用稳定换行和缩进生成的完整 C# 源码。</returns>
        private static string BuildSource(Action<RootCode> build)
        {
            if (build == null) throw new ArgumentNullException(nameof(build));
            return CodeGenKit.GenerateToString(root =>
            {
                root.Using("UnityEngine")
                    .Using("UnityEngine.UI")
                    .Using("YokiFrame")
                    .EmptyLine();
                build(root);
            });
        }

        /// <summary>生成面板用户脚本，包含数据类型和最小生命周期模板。</summary>
        private static string BuildPanelUserSource(UIKitPanelCodeLayout layout)
        {
            return BuildSource(root => root.Namespace(layout.ScriptNamespace, scope =>
            {
                scope.Class(layout.PanelName + "Data", "IUIData", false, false, data =>
                    data.AsSealed().WithAttribute("System.Serializable"));
                scope.EmptyLine();
                scope.Class(layout.PanelName, layout.BaseClassName, true, false, panel =>
                {
                    panel.ProtectedOverrideVoid("OnInit", method => method
                        .WithParameter("IUIData", "data", "null")
                        .WithBody(body => body.Custom(
                            "mData = data as " + layout.PanelName + "Data ?? new " + layout.PanelName + "Data();")));
                    if (!string.Equals(
                            layout.CodeTemplate,
                            UIKitPanelGenerationRequest.MINIMAL_TEMPLATE,
                            StringComparison.Ordinal))
                    {
                        panel.EmptyLine();
                        panel.ProtectedOverrideVoid("OnOpen", method => method
                            .WithParameter("IUIData", "data", "null")
                            .WithBody(body => body.Custom(
                                "mData = data as " + layout.PanelName + "Data ?? mData;")));
                        panel.EmptyLine();
                        panel.ProtectedOverrideVoid("OnShow", default);
                        panel.EmptyLine();
                        panel.ProtectedOverrideVoid("OnHide", default);
                    }

                    panel.EmptyLine();
                    panel.ProtectedOverrideVoid("OnClose", default);
                    if (layout.IsDialogTemplate)
                    {
                        // UIDialogPanel 把内容绑定定义为抽象方法，用户脚本必须生成可编译的重写。
                        panel.EmptyLine();
                        panel.ProtectedOverrideVoid("SetupDialog", method => method
                            .WithParameter("DialogConfig", "config"));
                    }
                });
            }));
        }

        /// <summary>生成面板 Designer 字段、数据属性和清理钩子。</summary>
        private static string BuildPanelDesignerSource(
            UIKitPanelCodeLayout layout,
            List<UIKitBindNode> nodes)
        {
            return BuildSource(root => root.Namespace(layout.ScriptNamespace, scope =>
                scope.Class(layout.PanelName, default, true, false, panel =>
                {
                    AppendFields(panel, nodes, layout);
                    panel.Field(layout.PanelName + "Data", "mData", field =>
                        field.WithAccess(AccessModifier.Private).WithAttribute("SerializeField"));
                    panel.EmptyLine();
                    panel.Property(layout.PanelName + "Data", "Data", property => property
                        .WithAccess(AccessModifier.Public)
                        .WithExpressionBody("mData"));
                    panel.EmptyLine();
                    panel.ProtectedOverrideVoid("ClearUIComponents", method => method
                        .WithBody(body => AppendClearFields(body, nodes)));
                })));
        }

        /// <summary>递归生成 Element/Component 用户脚本和 Designer 文件。</summary>
        private static void AddNodeSources(
            UIKitPanelCodeLayout layout,
            List<UIKitBindNode> nodes,
            Dictionary<string, string> sources,
            IUIKitCodeTemplate template,
            Dictionary<string, string> relocations = null)
        {
            for (var index = 0; index < nodes.Count; index++)
            {
                UIKitBindNode node = nodes[index];
                if (node.Strategy.OutputKind == UIKitBindOutputKind.Element
                    || node.Strategy.OutputKind == UIKitBindOutputKind.Component)
                {
                    string userPath = node.Strategy.OutputKind == UIKitBindOutputKind.Element
                        ? layout.GetElementPath(node.TypeName, false)
                        : layout.GetComponentPath(node.TypeName, false);
                    string designerPath = node.Strategy.OutputKind == UIKitBindOutputKind.Element
                        ? layout.GetElementPath(node.TypeName, true)
                        : layout.GetComponentPath(node.TypeName, true);
                    AddIfMissing(
                        sources,
                        userPath,
                        relocations,
                        ApplyTemplate(
                            template,
                            UIKitCodeTemplatePart.BindingUser,
                            CreateTemplateContext(
                                layout,
                                node.TypeName,
                                node.Strategy.OutputKind.ToString(),
                                node.Strategy.OutputKind.ToString()),
                            BuildGeneratedUserSource(layout, node)));
                    AddSource(
                        sources,
                        designerPath,
                        ApplyTemplate(
                            template,
                            UIKitCodeTemplatePart.BindingDesigner,
                            CreateTemplateContext(
                                layout,
                                node.TypeName,
                                node.Strategy.OutputKind.ToString(),
                                node.Strategy.OutputKind.ToString()),
                            BuildGeneratedDesignerSource(layout, node)));
                    AddNodeSources(layout.ForChildren(node), node.Children, sources, template, relocations);
                }
                else
                {
                    AddNodeSources(layout, node.Children, sources, template, relocations);
                }
            }
        }

        /// <summary>生成一个 Element 或 Component 的用户 partial。</summary>
        private static string BuildGeneratedUserSource(
            UIKitPanelCodeLayout layout,
            UIKitBindNode node)
        {
            string namespaceName = node.Strategy.OutputKind == UIKitBindOutputKind.Element
                ? layout.GetElementNamespace()
                : layout.ScriptNamespace;
            string parent = node.Strategy.OutputKind == UIKitBindOutputKind.Element
                ? "UIElement"
                : "UIComponent";
            return BuildSource(root => root.Namespace(namespaceName, scope =>
                scope.Class(node.TypeName, parent, true, false, default)));
        }

        /// <summary>生成一个 Element 或 Component 的 Designer partial。</summary>
        private static string BuildGeneratedDesignerSource(
            UIKitPanelCodeLayout layout,
            UIKitBindNode node)
        {
            string namespaceName = node.Strategy.OutputKind == UIKitBindOutputKind.Element
                ? layout.GetElementNamespace()
                : layout.ScriptNamespace;
            return BuildBindingOwnerDesignerSource(
                layout.ForChildren(node),
                namespaceName,
                node.TypeName,
                node.Children);
        }

        /// <summary>生成一个已经存在的绑定 owner partial Designer。</summary>
        private static string BuildBindingOwnerDesignerSource(
            UIKitPanelCodeLayout layout,
            string namespaceName,
            string typeName,
            List<UIKitBindNode> nodes)
        {
            return BuildSource(root => root.Namespace(namespaceName, scope =>
                scope.Class(typeName, default, true, false, generated =>
                {
                    AppendFields(generated, nodes, layout);
                    generated.EmptyLine();
                    generated.VoidMethod("Clear", method => method
                        .WithBody(body => AppendClearFields(body, nodes)));
                })));
        }

        /// <summary>创建不泄漏内部扫描节点的项目模板上下文。</summary>
        /// <param name="layout">当前代码布局。</param>
        /// <param name="ownerTypeName">当前文件 owner 类型名。</param>
        /// <param name="ownerKind">Panel、Element 或 Component。</param>
        /// <param name="bindingKind">当前绑定输出类型。</param>
        /// <returns>供模板转换器使用的公开上下文。</returns>
        private static UIKitCodeTemplateContext CreateTemplateContext(
            UIKitPanelCodeLayout layout,
            string ownerTypeName,
            string ownerKind,
            string bindingKind)
        {
            return new UIKitCodeTemplateContext(
                layout.PanelName,
                layout.ScriptNamespace,
                ownerTypeName,
                ownerKind,
                bindingKind);
        }

        /// <summary>调用项目模板转换源码并规范化换行，仍由外层事务负责落盘。</summary>
        /// <param name="template">当前模板。</param>
        /// <param name="part">源码文件角色。</param>
        /// <param name="context">模板上下文。</param>
        /// <param name="source">CodeGenKit 默认源码。</param>
        /// <returns>转换后的完整源码。</returns>
        private static string ApplyTemplate(
            IUIKitCodeTemplate template,
            UIKitCodeTemplatePart part,
            UIKitCodeTemplateContext context,
            string source)
        {
            string transformed = template.Transform(part, context, source);
            if (string.IsNullOrWhiteSpace(transformed))
            {
                throw new InvalidOperationException(
                    "UIKit 代码模板返回了空源码: " + template.Name + "/" + part);
            }

            string normalized = transformed.Replace("\r\n", "\n").Replace('\r', '\n');
            if (IsDesignerPart(part)
                && !normalized.StartsWith(AUTO_GENERATED_HEADER, StringComparison.Ordinal))
            {
                normalized = AUTO_GENERATED_HEADER + normalized;
            }

            return normalized;
        }

        /// <summary>判断当前源码文件角色是否属于不可直接编辑的 Designer 文件。</summary>
        private static bool IsDesignerPart(UIKitCodeTemplatePart part)
        {
            return part == UIKitCodeTemplatePart.PanelDesigner
                || part == UIKitCodeTemplatePart.BindingDesigner;
        }

        /// <summary>把节点字段写入 owner class，重复生成类型不创建第二个引用字段。</summary>
        private static void AppendFields(
            ICodeScope scope,
            List<UIKitBindNode> nodes,
            UIKitPanelCodeLayout layout)
        {
            for (var index = 0; index < nodes.Count; index++)
            {
                UIKitBindNode node = nodes[index];
                if (node.IsRepeated || node.Strategy.OutputKind == UIKitBindOutputKind.Marker)
                    continue;
                string typeName = GetFieldType(layout, node);
                if (string.IsNullOrWhiteSpace(typeName)) continue;
                scope.Field(typeName, node.FieldName, field => field.WithAccess(AccessModifier.Public));
            }
        }

        /// <summary>生成 owner 清理方法中的字段归零语句。</summary>
        private static void AppendClearFields(ICodeScope scope, List<UIKitBindNode> nodes)
        {
            for (var index = 0; index < nodes.Count; index++)
            {
                UIKitBindNode node = nodes[index];
                if (!node.IsRepeated && node.Strategy.OutputKind != UIKitBindOutputKind.Marker)
                    scope.Custom(node.FieldName + " = default;");
            }
        }

        /// <summary>按绑定输出形态计算 C# 字段类型表达式；项目命名空间使用普通限定名，不添加 global:: 前缀。</summary>
        private static string GetFieldType(UIKitPanelCodeLayout layout, UIKitBindNode node)
        {
            switch (node.Strategy.OutputKind)
            {
                case UIKitBindOutputKind.Member:
                    return node.TypeName;
                case UIKitBindOutputKind.Element:
                case UIKitBindOutputKind.Component:
                    return layout.GetFullTypeName(node.Strategy.OutputKind, node.TypeName);
                default:
                    return string.Empty;
            }
        }

        /// <summary>只为不存在的用户脚本添加源，保留用户已有 partial 内容。</summary>
        private static void AddIfMissing(
            Dictionary<string, string> sources,
            string assetPath,
            Dictionary<string, string> relocations,
            string source)
        {
            if (relocations != null)
                foreach (string destination in relocations.Values)
                    if (string.Equals(destination, assetPath, StringComparison.OrdinalIgnoreCase)) return;
            if (!File.Exists(UIKitPanelCodeLayout.ToAbsolutePath(assetPath)))
                AddSource(sources, assetPath, source);
        }

        /// <summary>添加生成源并拒绝同一路径产生不同内容。</summary>
        private static void AddSource(
            Dictionary<string, string> sources,
            string assetPath,
            string source)
        {
            if (sources.TryGetValue(assetPath, out string existing)
                && !string.Equals(existing, source, StringComparison.Ordinal))
                throw new InvalidOperationException("多个 Bind 生成类型映射到同一文件: " + assetPath);
            sources[assetPath] = source;
        }

    }
}
#endif
