using System;
using System.Collections.Generic;

namespace YokiFrame
{
    public static partial class TableKitSourceCodeGenerator
    {
        /// <summary>生成动态 Luban manager 对应的强类型 TableKit 门面。</summary>
        /// <param name="tablesType">由 `topModule + manager` 得到的完整类型名。</param>
        /// <param name="editorDataPath">Editor/Tools 直接读取配置表时使用的项目路径。</param>
        /// <param name="tableNames">当前 Luban manager 构造函数实际请求的表资源名。</param>
        /// <returns>固定为 C# 9 的 TableKit 门面源码。</returns>
        public static string BuildFacadeSource(
            string tablesType,
            string editorDataPath,
            IReadOnlyList<string> tableNames)
        {
            string managerTypeName = "global::" + CodeGenKit.RequireQualifiedName(tablesType, nameof(tablesType));
            string editorPathLiteral = EscapeCSharpString(NormalizeDefaultEditorDataPath(editorDataPath));
            string[] normalizedTableNames = RequireTableNames(tableNames);
            return CodeGenKit.GenerateToString(root =>
            {
                CodeGenLineBuilder source = CodeGenKit.Lines(root);
                AppendFacadeHeader(source);
                AppendFacadeRuntimeSettings(source);
                AppendFacadeState(source, managerTypeName, normalizedTableNames);
                AppendFacadeSynchronousApi(source, managerTypeName);
                AppendFacadeAsynchronousApi(source, managerTypeName);
                AppendFacadeCleanup(source);
                AppendFacadeEditorApi(source, managerTypeName, editorPathLiteral);
                source.AppendLine("    }").AppendLine("}");
            });
        }

        /// <summary>写入生成标记、依赖 using 和固定 YokiFrame 门面声明。</summary>
        /// <param name="source">目标逐行生成器。</param>
        private static void AppendFacadeHeader(CodeGenLineBuilder source)
        {
            source.AppendLine("// <auto-generated>")
                .AppendLine("// 由 YokiFrame TableKit 通过 CodeGenKit 生成，请勿手动修改。")
                .AppendLine("// </auto-generated>")
                .AppendLine()
                .AppendLine("using System;")
                .AppendLine("using System.Threading;")
                .AppendLine("#if UNITY_EDITOR || (GODOT && TOOLS)")
                .AppendLine("using System.IO;")
                .AppendLine("using System.Reflection;")
                .AppendLine("#endif")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("using Cysharp.Threading.Tasks;")
                .AppendLine("#else")
                .AppendLine("using System.Threading.Tasks;")
                .AppendLine("#endif")
                .AppendLine()
                .AppendLine("namespace " + TABLEKIT_NAMESPACE)
                .AppendLine("{")
                .AppendLine("    /// <summary>当前 Luban target 的强类型配置表入口。</summary>")
                .AppendLine("    public static class TableKit")
                .AppendLine("    {");
        }

        /// <summary>写入稳定 Runtime Settings 键和资源读取模式。</summary>
        /// <param name="source">目标逐行生成器。</param>
        private static void AppendFacadeRuntimeSettings(CodeGenLineBuilder source)
        {
            source.AppendLine("        private const string SETTINGS_KIT = \"" + TableKitSettings.KIT_NAME + "\";")
                .AppendLine("        private const string RUNTIME_PATH_PATTERN_KEY = \"" + TableKitSettings.RUNTIME_PATH_PATTERN_KEY + "\";")
                .AppendLine("        private const string USE_RAW_RESOURCE_LOADING_KEY = \"" + TableKitSettings.USE_RAW_RESOURCE_LOADING_KEY + "\";")
                .AppendLine()
                .AppendLine("        /// <summary>从当前宿主 Runtime Settings 获取传给 Loader 的路径模板。</summary>")
                .AppendLine("        public static string RuntimePathPattern => KitSettings.GetString(SETTINGS_KIT, RUNTIME_PATH_PATTERN_KEY, string.Empty);")
                .AppendLine()
                .AppendLine("        /// <summary>获取 Loader 是否通过原始资源能力读取表数据。</summary>")
                .AppendLine("        public static bool UseRawResourceLoading => KitSettings.GetBool(SETTINGS_KIT, USE_RAW_RESOURCE_LOADING_KEY, true);")
                .AppendLine()
                .AppendLine("        private static TableDataResourceLoadMode ResourceLoadMode => UseRawResourceLoading")
                .AppendLine("            ? TableDataResourceLoadMode.Raw")
                .AppendLine("            : TableDataResourceLoadMode.Asset;")
                .AppendLine();
        }

        /// <summary>写入 Runtime manager 状态、Loader 注入和强类型访问属性。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        /// <param name="tableNames">异步默认 Loader 需要预加载的表资源名。</param>
        private static void AppendFacadeState(
            CodeGenLineBuilder source,
            string managerTypeName,
            IReadOnlyList<string> tableNames)
        {
            source.AppendLine("        private static " + managerTypeName + " sTables;")
                .AppendLine("        private static ITableDataLoader sLoader;")
                .AppendLine("        /// <summary>保护异步初始化的互斥信号量，确保并发调用只执行一次初始化。</summary>")
                .AppendLine("        private static readonly SemaphoreSlim sInitSemaphore = new SemaphoreSlim(1, 1);");
            AppendTableNames(source, tableNames);
            source.AppendLine()
                .AppendLine("        /// <summary>获取当前是否已经初始化表管理器。</summary>")
                .AppendLine("        public static bool Initialized => sTables != null;")
                .AppendLine()
                .AppendLine("        /// <summary>获取已初始化的 Luban 表管理器。</summary>")
                .AppendLine("        public static " + managerTypeName + " Tables => sTables ?? throw new InvalidOperationException(\"TableKit 尚未初始化。\");")
                .AppendLine()
                .AppendLine("        /// <summary>覆盖默认 ResKit 表管理器加载器。</summary>")
                .AppendLine("        /// <param name=\"loader\">项目自定义的资源读取和 manager 创建实现。</param>")
                .AppendLine("        public static void SetLoader(ITableDataLoader loader)")
                .AppendLine("        {")
                .AppendLine("            sLoader = loader ?? throw new ArgumentNullException(nameof(loader));")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>获取显式 Loader，未设置时惰性创建共享 ResKit 默认实现。</summary>")
                .AppendLine("        /// <returns>本次 TableKit 初始化使用的 Loader。</returns>")
                .AppendLine("        private static ITableDataLoader GetLoader()")
                .AppendLine("        {")
                .AppendLine("            if (sLoader == null) sLoader = new ResKitTableDataLoader(sTableNames);")
                .AppendLine("            return sLoader;")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>写入由 Luban manager 源码提取的稳定表资源名清单。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="tableNames">去重并保持 manager 请求顺序的表资源名。</param>
        private static void AppendTableNames(CodeGenLineBuilder source, IReadOnlyList<string> tableNames)
        {
            source.AppendLine("        private static readonly string[] sTableNames =")
                .AppendLine("        {");
            for (int index = 0; index < tableNames.Count; index++)
            {
                source.AppendLine("            \"" + EscapeCSharpString(tableNames[index]) + "\",");
            }
            source.AppendLine("        };");
        }

        /// <summary>写入同步初始化、加载和 Loader 调用。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        private static void AppendFacadeSynchronousApi(CodeGenLineBuilder source, string managerTypeName)
        {
            source.AppendLine("        /// <summary>按 Runtime Settings 同步初始化表管理器。</summary>")
                .AppendLine("        public static void Init()")
                .AppendLine("        {")
                .AppendLine("            if (sTables != null) return;")
                .AppendLine("            sTables = LoadTables(RuntimePathPattern);")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>按默认资源定位同步初始化并返回表管理器。</summary>")
                .AppendLine("        /// <returns>已初始化的强类型表管理器。</returns>")
                .AppendLine("        public static " + managerTypeName + " Load()")
                .AppendLine("        {")
                .AppendLine("            Init();")
                .AppendLine("            return Tables;")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>按调用方提供的路径模板同步初始化表管理器。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">交给项目 Loader 的运行时路径模板。</param>")
                .AppendLine("        public static void Init(string resourcePathPattern)")
                .AppendLine("        {")
                .AppendLine("            if (sTables != null) return;")
                .AppendLine("            sTables = LoadTables(resourcePathPattern);")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>同步初始化并返回强类型表管理器。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">交给项目 Loader 的运行时路径模板。</param>")
                .AppendLine("        /// <returns>已初始化的强类型表管理器。</returns>")
                .AppendLine("        public static " + managerTypeName + " Load(string resourcePathPattern)")
                .AppendLine("        {")
                .AppendLine("            Init(resourcePathPattern);")
                .AppendLine("            return Tables;")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>调用当前 Loader 并校验实际 manager 类型。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">包含表名占位符的运行时路径模板。</param>")
                .AppendLine("        /// <returns>类型与当前 target 匹配的表管理器。</returns>")
                .AppendLine("        private static " + managerTypeName + " LoadTables(string resourcePathPattern)")
                .AppendLine("        {")
                .AppendLine("            if (string.IsNullOrWhiteSpace(resourcePathPattern)) throw new InvalidOperationException(\"TableKit 运行时地址模板为空。\");")
                .AppendLine("            " + managerTypeName + " tables = GetLoader().Load<" + managerTypeName + ">(resourcePathPattern, ResourceLoadMode);")
                .AppendLine("            return tables ?? throw new InvalidOperationException(\"TableKit Loader 返回了空表管理器。\");")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>写入 Task/UniTask 异步初始化、加载和 Loader 调用。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        private static void AppendFacadeAsynchronousApi(CodeGenLineBuilder source, string managerTypeName)
        {
            AppendFacadeDefaultAsynchronousApi(source, managerTypeName);
            AppendFacadeExplicitAsynchronousApi(source, managerTypeName);
            AppendFacadeAsynchronousLoader(source, managerTypeName);
        }

        /// <summary>写入使用 Runtime Settings 的无参数异步入口。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        private static void AppendFacadeDefaultAsynchronousApi(CodeGenLineBuilder source, string managerTypeName)
        {
            source.AppendLine("        /// <summary>按 Runtime Settings 异步初始化表管理器。</summary>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        public static async UniTask InitAsync()")
                .AppendLine("#else")
                .AppendLine("        public static async Task InitAsync()")
                .AppendLine("#endif")
                .AppendLine("        {")
                .AppendLine("            if (sTables != null) return;")
                .AppendLine("            await sInitSemaphore.WaitAsync();")
                .AppendLine("            try")
                .AppendLine("            {")
                .AppendLine("                if (sTables != null) return;")
                .AppendLine("                sTables = await LoadTablesAsync(RuntimePathPattern);")
                .AppendLine("            }")
                .AppendLine("            finally")
                .AppendLine("            {")
                .AppendLine("                sInitSemaphore.Release();")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>按默认资源定位异步初始化并返回表管理器。</summary>")
                .AppendLine("        /// <returns>异步返回已初始化的强类型表管理器。</returns>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        public static async UniTask<" + managerTypeName + "> LoadAsync()")
                .AppendLine("#else")
                .AppendLine("        public static async Task<" + managerTypeName + "> LoadAsync()")
                .AppendLine("#endif")
                .AppendLine("        {")
                .AppendLine("            await InitAsync();")
                .AppendLine("            return Tables;")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>写入允许覆盖运行时路径模板的异步入口。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        private static void AppendFacadeExplicitAsynchronousApi(CodeGenLineBuilder source, string managerTypeName)
        {
            source.AppendLine("        /// <summary>按调用方提供的路径模板异步初始化表管理器。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">交给项目 Loader 的运行时路径模板。</param>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        public static async UniTask InitAsync(string resourcePathPattern)")
                .AppendLine("#else")
                .AppendLine("        public static async Task InitAsync(string resourcePathPattern)")
                .AppendLine("#endif")
                .AppendLine("        {")
                .AppendLine("            if (sTables != null) return;")
                .AppendLine("            await sInitSemaphore.WaitAsync();")
                .AppendLine("            try")
                .AppendLine("            {")
                .AppendLine("                if (sTables != null) return;")
                .AppendLine("                sTables = await LoadTablesAsync(resourcePathPattern);")
                .AppendLine("            }")
                .AppendLine("            finally")
                .AppendLine("            {")
                .AppendLine("                sInitSemaphore.Release();")
                .AppendLine("            }")
                .AppendLine("        }")
                .AppendLine()
                .AppendLine("        /// <summary>异步初始化并返回强类型表管理器。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">交给项目 Loader 的运行时路径模板。</param>")
                .AppendLine("        /// <returns>异步返回已初始化的强类型表管理器。</returns>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        public static async UniTask<" + managerTypeName + "> LoadAsync(string resourcePathPattern)")
                .AppendLine("#else")
                .AppendLine("        public static async Task<" + managerTypeName + "> LoadAsync(string resourcePathPattern)")
                .AppendLine("#endif")
                .AppendLine("        {")
                .AppendLine("            await InitAsync(resourcePathPattern);")
                .AppendLine("            return Tables;")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>写入异步 Loader 调用和空值校验。</summary>
        /// <param name="source">目标逐行生成器。</param>
        /// <param name="managerTypeName">完整 Luban manager 类型表达式。</param>
        private static void AppendFacadeAsynchronousLoader(CodeGenLineBuilder source, string managerTypeName)
        {
            source.AppendLine("        /// <summary>异步调用当前 Loader 并校验实际 manager 类型。</summary>")
                .AppendLine("        /// <param name=\"resourcePathPattern\">包含表名占位符的运行时路径模板。</param>")
                .AppendLine("        /// <returns>类型与当前 target 匹配的表管理器。</returns>")
                .AppendLine("#if YOKIFRAME_UNITASK_SUPPORT")
                .AppendLine("        private static async UniTask<" + managerTypeName + "> LoadTablesAsync(string resourcePathPattern)")
                .AppendLine("#else")
                .AppendLine("        private static async Task<" + managerTypeName + "> LoadTablesAsync(string resourcePathPattern)")
                .AppendLine("#endif")
                .AppendLine("        {")
                .AppendLine("            if (string.IsNullOrWhiteSpace(resourcePathPattern)) throw new InvalidOperationException(\"TableKit 运行时地址模板为空。\");")
                .AppendLine("            " + managerTypeName + " tables = await GetLoader().LoadAsync<" + managerTypeName + ">(resourcePathPattern, ResourceLoadMode);")
                .AppendLine("            return tables ?? throw new InvalidOperationException(\"TableKit Loader 返回了空表管理器。\");")
                .AppendLine("        }")
                .AppendLine();
        }

        /// <summary>写入清理 Runtime manager，并在 Editor/Tools 下同步清理编辑器缓存。</summary>
        /// <param name="source">目标逐行生成器。</param>
        private static void AppendFacadeCleanup(CodeGenLineBuilder source)
        {
            source.AppendLine("        /// <summary>清理已加载的 Runtime 与 Editor 表缓存，保留已注入 Loader。</summary>")
                .AppendLine("        public static void Clear()")
                .AppendLine("        {")
                .AppendLine("            sTables = null;")
                .AppendLine("#if UNITY_EDITOR || (GODOT && TOOLS)")
                .AppendLine("            sTablesEditor = null;")
                .AppendLine("#endif")
                .AppendLine("        }");
        }

        /// <summary>校验并去重 manager 请求的表资源名，避免异步预加载重复读取。</summary>
        /// <param name="tableNames">Application 从 Luban manager 源码提取的资源名。</param>
        /// <returns>保持首次出现顺序的资源名数组。</returns>
        private static string[] RequireTableNames(IReadOnlyList<string> tableNames)
        {
            if (tableNames == null) throw new ArgumentNullException(nameof(tableNames));
            List<string> result = new(tableNames.Count);
            HashSet<string> uniqueNames = new(StringComparer.Ordinal);
            for (int index = 0; index < tableNames.Count; index++)
            {
                string tableName = tableNames[index];
                if (string.IsNullOrWhiteSpace(tableName))
                {
                    throw new ArgumentException("Luban manager 包含空表资源名。", nameof(tableNames));
                }
                if (uniqueNames.Add(tableName)) result.Add(tableName);
            }
            return result.ToArray();
        }
    }
}
